# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python package tests

on:
  # Triggers the workflow on push or pull request events but only for non-docs commits
  push:
    paths-ignore:
      - CITATION.cff
      - .github/workflows/citation-cff.yml
  pull_request:
    paths-ignore:
      - CITATION.cff
      - .github/workflows/citation-cff.yml

jobs:
  lint:
    name: Lint with flake8 and black
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        if [ -f requirements-lint.txt ]; then pip install -r requirements-lint.txt; else pip install .[dev]; fi
    - name: Lint with flake8
      run: flake8 . --count --show-source --statistics
    - name: Check formatting with black
      run: black --check .

  build:
    name: Test on Python ${{ matrix.python-version }} and ${{ matrix.os }}
    needs: lint # don't run if linting failed
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        os:
        - ubuntu-latest
        - windows-latest
        # macOS tests do not give the same answer for the symmetry points when using
        # pm-symmetry since bumping dependencies beyond python3.9 - this function purely
        # calls soprano, so the underlying issue is probably there. Disable for now.
        # - macOS-14

    steps:
    - uses: actions/checkout@v2
    - name: Install apt packages
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libopenblas-dev
    - name: Install choco packages
      if: matrix.os == 'windows-latest'
      run: choco install pkgconfiglite
    - name: Setup conda
      if: matrix.os == 'windows-latest' && matrix.python-version == '3.14'
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
    - name: Install conda packages
      if: matrix.os == 'windows-latest' && matrix.python-version == '3.14'
      run: conda install openblas
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install build dependencies
      run: pip install pybind11==3.0.1 scipy-openblas==0.3.30.0.4
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
      shell: bash # Windows runners have Git Bash installed so this should work on all runners
    - name: Install package
      run: pip install -e .
    - name: Test with pytest
      run: pytest --cov pymuonsuite --cov-report xml
    - name: Upload to Codecov
      if: matrix.python-version == '3.11' && matrix.os == 'ubuntu-latest'
      uses: codecov/codecov-action@v3
